import { execSync } from 'node:child_process'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

// The git SHA this bundle was built from. 'dev' when git is unavailable —
// generate-version.mjs (which writes public/version.json) degrades the same way,
// so a no-git environment always compares "dev" against "dev" and shows nothing.
const BUILD_SHA = (() => {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim()
  } catch {
    return 'dev'
  }
})()

// https://vite.dev/config/
// NOTE: public/version.json (the "latest build" answer the installed APK
// checks against) is generated by the "prebuild" npm script, BEFORE vite
// starts, so the file is in place when public/ is copied into dist/.
export default defineConfig({
  plugins: [react(), tailwindcss()],
  define: {
    __BUILD_SHA__: JSON.stringify(BUILD_SHA),
  },
})
